### ISSUE TITLE
Loader Script Crashes When Launched On Protosmasher

### ISSUE THREAD

**Issue by BluelyTASer** [HexaRG/rb64-better-replication#1]
https://user-images.githubusercontent.com/59511669/107956330-c7e1ef00-6f7d-11eb-965f-f63ed52b86b9.mp4

**Comment by HexaRG** [comment]
Oh I didn't make the script for Protosmasher
It was made for Synapse X but I just fixed a crash with the loader script but that was because it was not waiting for the game to load
